### PR TITLE
Log names of unknown buttons in layout config

### PR DESCRIPTION
**Pull request by proski**

### CODE REVIEW

**Comment by proski** [comment]
I'm getting that warning from alacritty under certain circumstances: https://github.com/alacritty/alacritty/pull/7079
Showing the button name helps users understand the problem.
The button name was `appmenu` in my case. Maybe it should be implemented?

**Comment by PolyMeilex** [comment]
Thanks, while at it, could we lower the severity of the log? Feells like warn is too much for something that is kinda expected.

**Comment by proski** [comment]
I've lowered the level to DEBUG.

**Comment by proski** [comment]
I have fixed the formatting to make the CI happy.

By the way, I suspect that the CI is using a very old version of rust for the format check, or perhaps it's picking up some non-standard settings.

**Comment by PolyMeilex** [comment]
> By the way, I suspect that the CI is using a very old version of rust for the format check, or perhaps it's picking up some non-standard settings.

Hymm, everything looks good to me when it comes to fmt version, my local 1.71.1 setup outputs same results as github CI:
```
rustup show
stable-x86_64-unknown-linux-gnu (default)
rustc 1.71.1 (eb26296b5 2023-08-03)
```
```
cargo fmt --version
rustfmt 1.5.2-stable (eb26296 2023-08-03)
```
```
cargo fmt --check
Diff in /home/poly/dev/sctk-adwaita/src/buttons.rs at line 167:
                 "appmenu" => {
                     debug!("Ignoring \"appmenu\" button");
                     continue;
-                },
+                }
                 _ => {
                     warn!("Ignoring unknown button type: {button}");
                     continue;
Diff in /home/poly/dev/sctk-adwaita/src/buttons.rs at line 174:
-                },
+                }
             };
 
             buttons.push(Button::new(button_kind));
```

**Pull request merged**
